//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient_Assignment3.Assignment3ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment3ServiceReference.Assignment3ServiceSoap")]
    public interface Assignment3ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse HelloWorld(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse> HelloWorldAsync(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWld", ReplyAction="*")]
        WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse HelloWld(WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse> HelloWldAsync(WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWld", Namespace="http://tempuri.org/", Order=0)]
        public WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequestBody Body;
        
        public HelloWldRequest() {
        }
        
        public HelloWldRequest(WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWldRequestBody {
        
        public HelloWldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponseBody Body;
        
        public HelloWldResponse() {
        }
        
        public HelloWldResponse(WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWldResult;
        
        public HelloWldResponseBody() {
        }
        
        public HelloWldResponseBody(string HelloWldResult) {
            this.HelloWldResult = HelloWldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Assignment3ServiceSoapChannel : WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment3ServiceSoapClient : System.ServiceModel.ClientBase<WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap>, WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap {
        
        public Assignment3ServiceSoapClient() {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWorld(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest inValue = new WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest();
            inValue.Body = new WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody();
            WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse retVal = ((WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse> WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWorldAsync(WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest inValue = new WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequest();
            inValue.Body = new WSClient_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody();
            return ((WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWld(WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest request) {
            return base.Channel.HelloWld(request);
        }
        
        public string HelloWld() {
            WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest inValue = new WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest();
            inValue.Body = new WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequestBody();
            WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse retVal = ((WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWld(inValue);
            return retVal.Body.HelloWldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse> WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWldAsync(WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest request) {
            return base.Channel.HelloWldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient_Assignment3.Assignment3ServiceReference.HelloWldResponse> HelloWldAsync() {
            WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest inValue = new WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequest();
            inValue.Body = new WSClient_Assignment3.Assignment3ServiceReference.HelloWldRequestBody();
            return ((WSClient_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWldAsync(inValue);
        }
    }
}
