//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "Assignment5ServiceSoap", Namespace = "http://tempuri.org/")]
public partial class Assignment5Service : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback CreateEmployeeOperationCompleted;

    private System.Threading.SendOrPostCallback ReadEmployeesOperationCompleted;

    private System.Threading.SendOrPostCallback UpdateEmployeeOperationCompleted;

    private System.Threading.SendOrPostCallback DeleteEmployeeOperationCompleted;

    /// <remarks/>
    public Assignment5Service()
    {
        this.Url = "http://localhost/WSAssignment5/Assignment5Service.asmx";
    }

    /// <remarks/>
    public event CreateEmployeeCompletedEventHandler CreateEmployeeCompleted;

    /// <remarks/>
    public event ReadEmployeesCompletedEventHandler ReadEmployeesCompleted;

    /// <remarks/>
    public event UpdateEmployeeCompletedEventHandler UpdateEmployeeCompleted;

    /// <remarks/>
    public event DeleteEmployeeCompletedEventHandler DeleteEmployeeCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateEmployee", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CreateEmployee(string no_, string firstName, string lastName, string jobTitle)
    {
        object[] results = this.Invoke("CreateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCreateEmployee(string no_, string firstName, string lastName, string jobTitle, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CreateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle}, callback, asyncState);
    }

    /// <remarks/>
    public string EndCreateEmployee(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void CreateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle)
    {
        this.CreateEmployeeAsync(no_, firstName, lastName, jobTitle, null);
    }

    /// <remarks/>
    public void CreateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle, object userState)
    {
        if ((this.CreateEmployeeOperationCompleted == null))
        {
            this.CreateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEmployeeOperationCompleted);
        }
        this.InvokeAsync("CreateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle}, this.CreateEmployeeOperationCompleted, userState);
    }

    private void OnCreateEmployeeOperationCompleted(object arg)
    {
        if ((this.CreateEmployeeCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateEmployeeCompleted(this, new CreateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadEmployees", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] ReadEmployees()
    {
        object[] results = this.Invoke("ReadEmployees", new object[0]);
        return ((string[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginReadEmployees(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ReadEmployees", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string[] EndReadEmployees(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }

    /// <remarks/>
    public void ReadEmployeesAsync()
    {
        this.ReadEmployeesAsync(null);
    }

    /// <remarks/>
    public void ReadEmployeesAsync(object userState)
    {
        if ((this.ReadEmployeesOperationCompleted == null))
        {
            this.ReadEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadEmployeesOperationCompleted);
        }
        this.InvokeAsync("ReadEmployees", new object[0], this.ReadEmployeesOperationCompleted, userState);
    }

    private void OnReadEmployeesOperationCompleted(object arg)
    {
        if ((this.ReadEmployeesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReadEmployeesCompleted(this, new ReadEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateEmployee", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateEmployee(string no_, string firstName, string lastName, string jobTitle)
    {
        this.Invoke("UpdateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle});
    }

    /// <remarks/>
    public System.IAsyncResult BeginUpdateEmployee(string no_, string firstName, string lastName, string jobTitle, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("UpdateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle}, callback, asyncState);
    }

    /// <remarks/>
    public void EndUpdateEmployee(System.IAsyncResult asyncResult)
    {
        this.EndInvoke(asyncResult);
    }

    /// <remarks/>
    public void UpdateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle)
    {
        this.UpdateEmployeeAsync(no_, firstName, lastName, jobTitle, null);
    }

    /// <remarks/>
    public void UpdateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle, object userState)
    {
        if ((this.UpdateEmployeeOperationCompleted == null))
        {
            this.UpdateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmployeeOperationCompleted);
        }
        this.InvokeAsync("UpdateEmployee", new object[] {
                    no_,
                    firstName,
                    lastName,
                    jobTitle}, this.UpdateEmployeeOperationCompleted, userState);
    }

    private void OnUpdateEmployeeOperationCompleted(object arg)
    {
        if ((this.UpdateEmployeeCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteEmployee", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DeleteEmployee(string no_)
    {
        this.Invoke("DeleteEmployee", new object[] {
                    no_});
    }

    /// <remarks/>
    public System.IAsyncResult BeginDeleteEmployee(string no_, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("DeleteEmployee", new object[] {
                    no_}, callback, asyncState);
    }

    /// <remarks/>
    public void EndDeleteEmployee(System.IAsyncResult asyncResult)
    {
        this.EndInvoke(asyncResult);
    }

    /// <remarks/>
    public void DeleteEmployeeAsync(string no_)
    {
        this.DeleteEmployeeAsync(no_, null);
    }

    /// <remarks/>
    public void DeleteEmployeeAsync(string no_, object userState)
    {
        if ((this.DeleteEmployeeOperationCompleted == null))
        {
            this.DeleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmployeeOperationCompleted);
        }
        this.InvokeAsync("DeleteEmployee", new object[] {
                    no_}, this.DeleteEmployeeOperationCompleted, userState);
    }

    private void OnDeleteEmployeeOperationCompleted(object arg)
    {
        if ((this.DeleteEmployeeCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CreateEmployeeCompletedEventHandler(object sender, CreateEmployeeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CreateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void ReadEmployeesCompletedEventHandler(object sender, ReadEmployeesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ReadEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ReadEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void UpdateEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void DeleteEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);