//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient2_Assignment3.Assignment3ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment3ServiceReference.Assignment3ServiceSoap")]
    public interface Assignment3ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse HelloWorld(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse> HelloWorldAsync(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxtFile", ReplyAction="*")]
        WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse TxtFile(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TxtFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse> TxtFileAsync(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxtFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxtFile", Namespace="http://tempuri.org/", Order=0)]
        public WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequestBody Body;
        
        public TxtFileRequest() {
        }
        
        public TxtFileRequest(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxtFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public TxtFileRequestBody() {
        }
        
        public TxtFileRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TxtFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TxtFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponseBody Body;
        
        public TxtFileResponse() {
        }
        
        public TxtFileResponse(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TxtFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TxtFileResult;
        
        public TxtFileResponseBody() {
        }
        
        public TxtFileResponseBody(string TxtFileResult) {
            this.TxtFileResult = TxtFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Assignment3ServiceSoapChannel : WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment3ServiceSoapClient : System.ServiceModel.ClientBase<WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap>, WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap {
        
        public Assignment3ServiceSoapClient() {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWorld(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest inValue = new WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest();
            inValue.Body = new WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody();
            WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse retVal = ((WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse> WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.HelloWorldAsync(WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest inValue = new WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequest();
            inValue.Body = new WSClient2_Assignment3.Assignment3ServiceReference.HelloWorldRequestBody();
            return ((WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.TxtFile(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest request) {
            return base.Channel.TxtFile(request);
        }
        
        public string TxtFile(string filename) {
            WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest inValue = new WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest();
            inValue.Body = new WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequestBody();
            inValue.Body.filename = filename;
            WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse retVal = ((WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).TxtFile(inValue);
            return retVal.Body.TxtFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse> WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap.TxtFileAsync(WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest request) {
            return base.Channel.TxtFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient2_Assignment3.Assignment3ServiceReference.TxtFileResponse> TxtFileAsync(string filename) {
            WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest inValue = new WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequest();
            inValue.Body = new WSClient2_Assignment3.Assignment3ServiceReference.TxtFileRequestBody();
            inValue.Body.filename = filename;
            return ((WSClient2_Assignment3.Assignment3ServiceReference.Assignment3ServiceSoap)(this)).TxtFileAsync(inValue);
        }
    }
}
