//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPClient1_Assignment6.Assignment6Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment6Reference.Assignment6ServiceSoap")]
    public interface Assignment6ServiceSoap {
        
        // CODEGEN: Generating message contract since element name MetaDataForEmployeeTableResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MetaDataForEmployeeTable", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse MetaDataForEmployeeTable(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MetaDataForEmployeeTable", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse> MetaDataForEmployeeTableAsync(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeeRelativesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeRelatives", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse EmployeeRelatives(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse> EmployeeRelativesAsync(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeeAbsent2004Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAbsent2004", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response EmployeeAbsent2004(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAbsent2004", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response> EmployeeAbsent2004Async(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request request);
        
        // CODEGEN: Generating message contract since element name EmployeeAbsentTheMostResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAbsentTheMost", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse EmployeeAbsentTheMost(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAbsentTheMost", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse> EmployeeAbsentTheMostAsync(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest request);
        
        // CODEGEN: Generating message contract since element name AllKeysResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllKeys", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse AllKeys(ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse> AllKeysAsync(ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name AllIndexesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse AllIndexes(ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse> AllIndexesAsync(ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name AllTableConstraintsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableConstraints", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse AllTableConstraints(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse> AllTableConstraintsAsync(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name AllTables1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTables1", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllTables1Response AllTables1(ERPClient1_Assignment6.Assignment6Reference.AllTables1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTables1", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables1Response> AllTables1Async(ERPClient1_Assignment6.Assignment6Reference.AllTables1Request request);
        
        // CODEGEN: Generating message contract since element name AllTables2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTables2", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllTables2Response AllTables2(ERPClient1_Assignment6.Assignment6Reference.AllTables2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTables2", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables2Response> AllTables2Async(ERPClient1_Assignment6.Assignment6Reference.AllTables2Request request);
        
        // CODEGEN: Generating message contract since element name AllColumns1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColumns1", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response AllColumns1(ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColumns1", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response> AllColumns1Async(ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request request);
        
        // CODEGEN: Generating message contract since element name AllColumns2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColumns2", ReplyAction="*")]
        ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response AllColumns2(ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColumns2", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response> AllColumns2Async(ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MetaDataForEmployeeTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MetaDataForEmployeeTable", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequestBody Body;
        
        public MetaDataForEmployeeTableRequest() {
        }
        
        public MetaDataForEmployeeTableRequest(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MetaDataForEmployeeTableRequestBody {
        
        public MetaDataForEmployeeTableRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MetaDataForEmployeeTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MetaDataForEmployeeTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponseBody Body;
        
        public MetaDataForEmployeeTableResponse() {
        }
        
        public MetaDataForEmployeeTableResponse(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MetaDataForEmployeeTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> MetaDataForEmployeeTableResult;
        
        public MetaDataForEmployeeTableResponseBody() {
        }
        
        public MetaDataForEmployeeTableResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> MetaDataForEmployeeTableResult) {
            this.MetaDataForEmployeeTableResult = MetaDataForEmployeeTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeRelatives", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequestBody Body;
        
        public EmployeeRelativesRequest() {
        }
        
        public EmployeeRelativesRequest(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeRelativesRequestBody {
        
        public EmployeeRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponseBody Body;
        
        public EmployeeRelativesResponse() {
        }
        
        public EmployeeRelativesResponse(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeRelativesResult;
        
        public EmployeeRelativesResponseBody() {
        }
        
        public EmployeeRelativesResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeRelativesResult) {
            this.EmployeeRelativesResult = EmployeeRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAbsent2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAbsent2004", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004RequestBody Body;
        
        public EmployeeAbsent2004Request() {
        }
        
        public EmployeeAbsent2004Request(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeAbsent2004RequestBody {
        
        public EmployeeAbsent2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAbsent2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAbsent2004Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004ResponseBody Body;
        
        public EmployeeAbsent2004Response() {
        }
        
        public EmployeeAbsent2004Response(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeAbsent2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsent2004Result;
        
        public EmployeeAbsent2004ResponseBody() {
        }
        
        public EmployeeAbsent2004ResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsent2004Result) {
            this.EmployeeAbsent2004Result = EmployeeAbsent2004Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAbsentTheMostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAbsentTheMost", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequestBody Body;
        
        public EmployeeAbsentTheMostRequest() {
        }
        
        public EmployeeAbsentTheMostRequest(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeAbsentTheMostRequestBody {
        
        public EmployeeAbsentTheMostRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAbsentTheMostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAbsentTheMostResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponseBody Body;
        
        public EmployeeAbsentTheMostResponse() {
        }
        
        public EmployeeAbsentTheMostResponse(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeAbsentTheMostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsentTheMostResult;
        
        public EmployeeAbsentTheMostResponseBody() {
        }
        
        public EmployeeAbsentTheMostResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsentTheMostResult) {
            this.EmployeeAbsentTheMostResult = EmployeeAbsentTheMostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllKeys", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllKeysRequestBody Body;
        
        public AllKeysRequest() {
        }
        
        public AllKeysRequest(ERPClient1_Assignment6.Assignment6Reference.AllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllKeysRequestBody {
        
        public AllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllKeysResponseBody Body;
        
        public AllKeysResponse() {
        }
        
        public AllKeysResponse(ERPClient1_Assignment6.Assignment6Reference.AllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllKeysResult;
        
        public AllKeysResponseBody() {
        }
        
        public AllKeysResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllKeysResult) {
            this.AllKeysResult = AllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllIndexes", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequestBody Body;
        
        public AllIndexesRequest() {
        }
        
        public AllIndexesRequest(ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllIndexesRequestBody {
        
        public AllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponseBody Body;
        
        public AllIndexesResponse() {
        }
        
        public AllIndexesResponse(ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllIndexesResult;
        
        public AllIndexesResponseBody() {
        }
        
        public AllIndexesResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllIndexesResult) {
            this.AllIndexesResult = AllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableConstraints", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequestBody Body;
        
        public AllTableConstraintsRequest() {
        }
        
        public AllTableConstraintsRequest(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllTableConstraintsRequestBody {
        
        public AllTableConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTableConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTableConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponseBody Body;
        
        public AllTableConstraintsResponse() {
        }
        
        public AllTableConstraintsResponse(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTableConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTableConstraintsResult;
        
        public AllTableConstraintsResponseBody() {
        }
        
        public AllTableConstraintsResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTableConstraintsResult) {
            this.AllTableConstraintsResult = AllTableConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTables1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTables1", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTables1RequestBody Body;
        
        public AllTables1Request() {
        }
        
        public AllTables1Request(ERPClient1_Assignment6.Assignment6Reference.AllTables1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllTables1RequestBody {
        
        public AllTables1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTables1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTables1Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTables1ResponseBody Body;
        
        public AllTables1Response() {
        }
        
        public AllTables1Response(ERPClient1_Assignment6.Assignment6Reference.AllTables1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTables1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables1Result;
        
        public AllTables1ResponseBody() {
        }
        
        public AllTables1ResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables1Result) {
            this.AllTables1Result = AllTables1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTables2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTables2", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTables2RequestBody Body;
        
        public AllTables2Request() {
        }
        
        public AllTables2Request(ERPClient1_Assignment6.Assignment6Reference.AllTables2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllTables2RequestBody {
        
        public AllTables2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllTables2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllTables2Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllTables2ResponseBody Body;
        
        public AllTables2Response() {
        }
        
        public AllTables2Response(ERPClient1_Assignment6.Assignment6Reference.AllTables2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllTables2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables2Result;
        
        public AllTables2ResponseBody() {
        }
        
        public AllTables2ResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables2Result) {
            this.AllTables2Result = AllTables2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllColumns1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllColumns1", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllColumns1RequestBody Body;
        
        public AllColumns1Request() {
        }
        
        public AllColumns1Request(ERPClient1_Assignment6.Assignment6Reference.AllColumns1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllColumns1RequestBody {
        
        public AllColumns1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllColumns1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllColumns1Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllColumns1ResponseBody Body;
        
        public AllColumns1Response() {
        }
        
        public AllColumns1Response(ERPClient1_Assignment6.Assignment6Reference.AllColumns1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllColumns1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns1Result;
        
        public AllColumns1ResponseBody() {
        }
        
        public AllColumns1ResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns1Result) {
            this.AllColumns1Result = AllColumns1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllColumns2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllColumns2", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllColumns2RequestBody Body;
        
        public AllColumns2Request() {
        }
        
        public AllColumns2Request(ERPClient1_Assignment6.Assignment6Reference.AllColumns2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllColumns2RequestBody {
        
        public AllColumns2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllColumns2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllColumns2Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment6.Assignment6Reference.AllColumns2ResponseBody Body;
        
        public AllColumns2Response() {
        }
        
        public AllColumns2Response(ERPClient1_Assignment6.Assignment6Reference.AllColumns2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllColumns2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns2Result;
        
        public AllColumns2ResponseBody() {
        }
        
        public AllColumns2ResponseBody(System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns2Result) {
            this.AllColumns2Result = AllColumns2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Assignment6ServiceSoapChannel : ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment6ServiceSoapClient : System.ServiceModel.ClientBase<ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap>, ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap {
        
        public Assignment6ServiceSoapClient() {
        }
        
        public Assignment6ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment6ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment6ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment6ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.MetaDataForEmployeeTable(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest request) {
            return base.Channel.MetaDataForEmployeeTable(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> MetaDataForEmployeeTable() {
            ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).MetaDataForEmployeeTable(inValue);
            return retVal.Body.MetaDataForEmployeeTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.MetaDataForEmployeeTableAsync(ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest request) {
            return base.Channel.MetaDataForEmployeeTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableResponse> MetaDataForEmployeeTableAsync() {
            ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.MetaDataForEmployeeTableRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).MetaDataForEmployeeTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeRelatives(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest request) {
            return base.Channel.EmployeeRelatives(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeRelatives() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeRelatives(inValue);
            return retVal.Body.EmployeeRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeRelativesAsync(ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest request) {
            return base.Channel.EmployeeRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesResponse> EmployeeRelativesAsync() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeRelativesRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeAbsent2004(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request request) {
            return base.Channel.EmployeeAbsent2004(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsent2004() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004RequestBody();
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeAbsent2004(inValue);
            return retVal.Body.EmployeeAbsent2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeAbsent2004Async(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request request) {
            return base.Channel.EmployeeAbsent2004Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Response> EmployeeAbsent2004Async() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsent2004RequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeAbsent2004Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeAbsentTheMost(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest request) {
            return base.Channel.EmployeeAbsentTheMost(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> EmployeeAbsentTheMost() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeAbsentTheMost(inValue);
            return retVal.Body.EmployeeAbsentTheMostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.EmployeeAbsentTheMostAsync(ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest request) {
            return base.Channel.EmployeeAbsentTheMostAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostResponse> EmployeeAbsentTheMostAsync() {
            ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.EmployeeAbsentTheMostRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).EmployeeAbsentTheMostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllKeys(ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest request) {
            return base.Channel.AllKeys(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllKeys() {
            ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllKeysRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllKeys(inValue);
            return retVal.Body.AllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllKeysAsync(ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest request) {
            return base.Channel.AllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllKeysResponse> AllKeysAsync() {
            ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllKeysRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllKeysRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllIndexes(ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest request) {
            return base.Channel.AllIndexes(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllIndexes() {
            ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllIndexes(inValue);
            return retVal.Body.AllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllIndexesAsync(ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest request) {
            return base.Channel.AllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllIndexesResponse> AllIndexesAsync() {
            ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllIndexesRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTableConstraints(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest request) {
            return base.Channel.AllTableConstraints(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTableConstraints() {
            ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTableConstraints(inValue);
            return retVal.Body.AllTableConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTableConstraintsAsync(ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest request) {
            return base.Channel.AllTableConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsResponse> AllTableConstraintsAsync() {
            ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequest();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTableConstraintsRequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTableConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllTables1Response ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTables1(ERPClient1_Assignment6.Assignment6Reference.AllTables1Request request) {
            return base.Channel.AllTables1(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables1() {
            ERPClient1_Assignment6.Assignment6Reference.AllTables1Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTables1Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTables1RequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllTables1Response retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTables1(inValue);
            return retVal.Body.AllTables1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables1Response> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTables1Async(ERPClient1_Assignment6.Assignment6Reference.AllTables1Request request) {
            return base.Channel.AllTables1Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables1Response> AllTables1Async() {
            ERPClient1_Assignment6.Assignment6Reference.AllTables1Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTables1Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTables1RequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTables1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllTables2Response ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTables2(ERPClient1_Assignment6.Assignment6Reference.AllTables2Request request) {
            return base.Channel.AllTables2(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllTables2() {
            ERPClient1_Assignment6.Assignment6Reference.AllTables2Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTables2Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTables2RequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllTables2Response retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTables2(inValue);
            return retVal.Body.AllTables2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables2Response> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllTables2Async(ERPClient1_Assignment6.Assignment6Reference.AllTables2Request request) {
            return base.Channel.AllTables2Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllTables2Response> AllTables2Async() {
            ERPClient1_Assignment6.Assignment6Reference.AllTables2Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllTables2Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllTables2RequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllTables2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllColumns1(ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request request) {
            return base.Channel.AllColumns1(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns1() {
            ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllColumns1RequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllColumns1(inValue);
            return retVal.Body.AllColumns1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllColumns1Async(ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request request) {
            return base.Channel.AllColumns1Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns1Response> AllColumns1Async() {
            ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllColumns1Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllColumns1RequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllColumns1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllColumns2(ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request request) {
            return base.Channel.AllColumns2(request);
        }
        
        public System.Collections.Generic.List<ERPClient1_Assignment6.Assignment6Reference.ArrayOfString> AllColumns2() {
            ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllColumns2RequestBody();
            ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response retVal = ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllColumns2(inValue);
            return retVal.Body.AllColumns2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response> ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap.AllColumns2Async(ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request request) {
            return base.Channel.AllColumns2Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment6.Assignment6Reference.AllColumns2Response> AllColumns2Async() {
            ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request inValue = new ERPClient1_Assignment6.Assignment6Reference.AllColumns2Request();
            inValue.Body = new ERPClient1_Assignment6.Assignment6Reference.AllColumns2RequestBody();
            return ((ERPClient1_Assignment6.Assignment6Reference.Assignment6ServiceSoap)(this)).AllColumns2Async(inValue);
        }
    }
}
