//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPClient1_Assignment5.Assignment5Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment5Reference.Assignment5ServiceSoap")]
    public interface Assignment5ServiceSoap {
        
        // CODEGEN: Generating message contract since element name no_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse CreateEmployee(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse> CreateEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name ReadEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployees", ReplyAction="*")]
        ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse ReadEmployees(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse> ReadEmployeesAsync(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name no_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse UpdateEmployee(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse> UpdateEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse DeleteEmployee(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse> DeleteEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(string no_, string firstName, string lastName, string jobTitle) {
            this.no_ = no_;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(bool CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadEmployees", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequestBody Body;
        
        public ReadEmployeesRequest() {
        }
        
        public ReadEmployeesRequest(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadEmployeesRequestBody {
        
        public ReadEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponseBody Body;
        
        public ReadEmployeesResponse() {
        }
        
        public ReadEmployeesResponse(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.ArrayOfString ReadEmployeesResult;
        
        public ReadEmployeesResponseBody() {
        }
        
        public ReadEmployeesResponseBody(ERPClient1_Assignment5.Assignment5Reference.ArrayOfString ReadEmployeesResult) {
            this.ReadEmployeesResult = ReadEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(string no_, string firstName, string lastName, string jobTitle) {
            this.no_ = no_;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(bool UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no_;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(string no_) {
            this.no_ = no_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody() {
        }
        
        public DeleteEmployeeResponseBody(bool DeleteEmployeeResult) {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Assignment5ServiceSoapChannel : ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment5ServiceSoapClient : System.ServiceModel.ClientBase<ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap>, ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap {
        
        public Assignment5ServiceSoapClient() {
        }
        
        public Assignment5ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment5ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment5ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment5ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.CreateEmployee(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public bool CreateEmployee(string no_, string firstName, string lastName, string jobTitle) {
            ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse retVal = ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse> ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.CreateEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeResponse> CreateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle) {
            ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.CreateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            return ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.ReadEmployees(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest request) {
            return base.Channel.ReadEmployees(request);
        }
        
        public ERPClient1_Assignment5.Assignment5Reference.ArrayOfString ReadEmployees() {
            ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequestBody();
            ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse retVal = ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).ReadEmployees(inValue);
            return retVal.Body.ReadEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse> ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.ReadEmployeesAsync(ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest request) {
            return base.Channel.ReadEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesResponse> ReadEmployeesAsync() {
            ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.ReadEmployeesRequestBody();
            return ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).ReadEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.UpdateEmployee(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public bool UpdateEmployee(string no_, string firstName, string lastName, string jobTitle) {
            ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse retVal = ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse> ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.UpdateEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeResponse> UpdateEmployeeAsync(string no_, string firstName, string lastName, string jobTitle) {
            ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.UpdateEmployeeRequestBody();
            inValue.Body.no_ = no_;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            return ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.DeleteEmployee(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public bool DeleteEmployee(string no_) {
            ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequestBody();
            inValue.Body.no_ = no_;
            ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse retVal = ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).DeleteEmployee(inValue);
            return retVal.Body.DeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse> ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap.DeleteEmployeeAsync(ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeResponse> DeleteEmployeeAsync(string no_) {
            ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest inValue = new ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequest();
            inValue.Body = new ERPClient1_Assignment5.Assignment5Reference.DeleteEmployeeRequestBody();
            inValue.Body.no_ = no_;
            return ((ERPClient1_Assignment5.Assignment5Reference.Assignment5ServiceSoap)(this)).DeleteEmployeeAsync(inValue);
        }
    }
}
